USE [master]
GO

/****** Object:  Database [resturantASP]    Script Date: 8/29/2022 11:15:57 PM ******/
CREATE DATABASE [resturantASP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'resturantASP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\resturantASP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'resturantASP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\resturantASP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [resturantASP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [resturantASP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [resturantASP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [resturantASP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [resturantASP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [resturantASP] SET ARITHABORT OFF 
GO

ALTER DATABASE [resturantASP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [resturantASP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [resturantASP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [resturantASP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [resturantASP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [resturantASP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [resturantASP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [resturantASP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [resturantASP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [resturantASP] SET  DISABLE_BROKER 
GO

ALTER DATABASE [resturantASP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [resturantASP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [resturantASP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [resturantASP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [resturantASP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [resturantASP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [resturantASP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [resturantASP] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [resturantASP] SET  MULTI_USER 
GO

ALTER DATABASE [resturantASP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [resturantASP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [resturantASP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [resturantASP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [resturantASP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [resturantASP] SET QUERY_STORE = OFF
GO

ALTER DATABASE [resturantASP] SET  READ_WRITE 
GO

